import { formatCell } from './format-cell'
import type { ReportExportPayload } from './types'

/** UTF-8 BOM helps Excel detect Bangla / Taka correctly. */
const BOM = '﻿'

function escape(field: unknown): string {
  const s = field == null ? '' : String(field)
  if (/[",\n]/.test(s)) return `"${s.replace(/"/g, '""')}"`
  return s
}

export function payloadToCsv(payload: ReportExportPayload): string {
  const lines: string[] = []
  lines.push(`"${payload.title}"`)
  lines.push(`"${payload.subtitle}"`)
  if (payload.comparisonLabel) lines.push(`"${payload.comparisonLabel}"`)
  lines.push(`"Generated by ${payload.generatedBy} on ${payload.generatedAt.toISOString()}"`)
  lines.push('')

  if (payload.kpis.length > 0) {
    lines.push('KPI,Value,Comparison')
    for (const k of payload.kpis) {
      lines.push([escape(k.label), escape(k.value), escape(k.comparison ?? '')].join(','))
    }
    lines.push('')
  }

  for (const table of payload.tables) {
    lines.push(`"${table.title}"`)
    lines.push(table.columns.map((c) => escape(c.label)).join(','))
    for (const row of table.rows) {
      lines.push(table.columns.map((c) => escape(formatCell(row[c.key], c.format))).join(','))
    }
    if (table.totals) {
      lines.push(table.columns.map((c) => escape(formatCell(table.totals![c.key], c.format))).join(','))
    }
    lines.push('')
  }

  if (payload.notes && payload.notes.length > 0) {
    lines.push('Notes')
    for (const n of payload.notes) lines.push(escape(n))
  }

  return BOM + lines.join('\r\n')
}
