import { Document, Page, View, Text, StyleSheet } from '@react-pdf/renderer'
import { formatCell } from './format-cell'
import type { ReportExportPayload, ExportTable } from './types'

const styles = StyleSheet.create({
  page:        { padding: 32, fontSize: 9, fontFamily: 'Helvetica' },
  header:      { borderBottomWidth: 2, borderBottomColor: '#4f46e5', paddingBottom: 8, marginBottom: 12 },
  title:       { fontSize: 16, fontWeight: 700, color: '#1e293b' },
  subtitle:    { fontSize: 10, color: '#475569', marginTop: 2 },
  meta:        { fontSize: 8, color: '#64748b', marginTop: 4 },

  kpiRow:      { flexDirection: 'row', flexWrap: 'wrap', marginBottom: 12, gap: 8 },
  kpi:         { width: '32%', borderWidth: 1, borderColor: '#e2e8f0', padding: 6 },
  kpiLabel:    { fontSize: 7, color: '#64748b', textTransform: 'uppercase' },
  kpiValue:    { fontSize: 12, fontWeight: 700, color: '#1e293b', marginTop: 2 },
  kpiCompare:  { fontSize: 7, color: '#475569', marginTop: 1 },

  tableTitle:  { fontSize: 11, fontWeight: 700, color: '#1e293b', marginTop: 8, marginBottom: 4 },
  table:       { borderWidth: 1, borderColor: '#e2e8f0', borderBottomWidth: 0 },
  tr:          { flexDirection: 'row', borderBottomWidth: 1, borderBottomColor: '#e2e8f0' },
  th:          { backgroundColor: '#4f46e5', color: 'white', padding: 4, fontSize: 8, fontWeight: 700 },
  td:          { padding: 4, fontSize: 8 },
  trEven:      { backgroundColor: '#f8fafc' },
  trTotal:     { backgroundColor: '#e2e8f0', fontWeight: 700 },

  footer:      { position: 'absolute', bottom: 16, left: 32, right: 32, fontSize: 7, color: '#94a3b8',
                 borderTopWidth: 1, borderTopColor: '#e2e8f0', paddingTop: 6, flexDirection: 'row', justifyContent: 'space-between' },
})

function alignStyle(a: 'left' | 'right' | 'center' | undefined) {
  if (a === 'right')  return { textAlign: 'right' as const }
  if (a === 'center') return { textAlign: 'center' as const }
  return { textAlign: 'left' as const }
}

function PdfTable({ table }: { table: ExportTable }) {
  const totalCols = table.columns.length
  const colWidth = `${(100 / totalCols).toFixed(2)}%`
  return (
    <View>
      <Text style={styles.tableTitle}>{table.title}</Text>
      <View style={styles.table}>
        <View style={styles.tr}>
          {table.columns.map((c) => (
            <Text key={c.key} style={[styles.th, alignStyle(c.align), { width: colWidth }]}>{c.label}</Text>
          ))}
        </View>
        {table.rows.map((row, i) => (
          <View key={i} style={[styles.tr, i % 2 === 0 ? styles.trEven : {}]}>
            {table.columns.map((c) => (
              <Text key={c.key} style={[styles.td, alignStyle(c.align), { width: colWidth }]}>
                {formatCell(row[c.key], c.format)}
              </Text>
            ))}
          </View>
        ))}
        {table.totals && (
          <View style={[styles.tr, styles.trTotal]}>
            {table.columns.map((c) => (
              <Text key={c.key} style={[styles.td, alignStyle(c.align), { width: colWidth }]}>
                {formatCell(table.totals![c.key], c.format)}
              </Text>
            ))}
          </View>
        )}
      </View>
    </View>
  )
}

export function ReportPdfDocument({ payload }: { payload: ReportExportPayload }) {
  return (
    <Document>
      <Page size="A4" style={styles.page} wrap>
        <View style={styles.header}>
          <Text style={styles.title}>{payload.title}</Text>
          <Text style={styles.subtitle}>{payload.subtitle}{payload.comparisonLabel ? ` · ${payload.comparisonLabel}` : ''}</Text>
          <Text style={styles.meta}>Generated by {payload.generatedBy} · {payload.generatedAt.toLocaleString('en-GB')}</Text>
        </View>

        {payload.kpis.length > 0 && (
          <View style={styles.kpiRow}>
            {payload.kpis.map((k) => (
              <View key={k.label} style={styles.kpi}>
                <Text style={styles.kpiLabel}>{k.label}</Text>
                <Text style={styles.kpiValue}>{k.value}</Text>
                {k.comparison && <Text style={styles.kpiCompare}>{k.comparison}</Text>}
              </View>
            ))}
          </View>
        )}

        {payload.tables.map((t) => <PdfTable key={t.title} table={t} />)}

        {payload.notes && payload.notes.length > 0 && (
          <View style={{ marginTop: 12 }}>
            <Text style={styles.tableTitle}>Notes</Text>
            {payload.notes.map((n, i) => <Text key={i} style={[styles.td, { padding: 0 }]}>• {n}</Text>)}
          </View>
        )}

        <Text style={styles.footer} fixed render={({ pageNumber, totalPages }) =>
          `Garden Centre Resort · Confidential   |   Page ${pageNumber} of ${totalPages}   |   ${payload.generatedAt.toLocaleDateString('en-GB')}`
        } />
      </Page>
    </Document>
  )
}
