import * as XLSX from 'xlsx'
import { formatCell, rawNumber } from './format-cell'
import type { ReportExportPayload, ExportTable } from './types'

const CURRENCY_FMT = '#,##0.00 "৳"'
const PERCENT_FMT  = '0.0"%"'
const NUMBER_FMT   = '#,##0'
const DATE_FMT     = 'd-mmm-yyyy'

function tableToSheet(table: ExportTable): XLSX.WorkSheet {
  const aoa: any[][] = []  // eslint-disable-line @typescript-eslint/no-explicit-any
  aoa.push([table.title])
  aoa.push(table.columns.map((c) => c.label))
  for (const row of table.rows) {
    aoa.push(table.columns.map((c) => {
      const raw = row[c.key]
      // Use raw numeric value for numeric formats so Excel treats them as numbers.
      if (c.format === 'currency' || c.format === 'percent' || c.format === 'number') {
        return rawNumber(raw) ?? ''
      }
      if (c.format === 'date' && raw) return new Date(String(raw))
      return formatCell(raw, c.format)
    }))
  }
  if (table.totals) {
    aoa.push(table.columns.map((c) => {
      const raw = table.totals![c.key]
      if (c.format === 'currency' || c.format === 'percent' || c.format === 'number') {
        return rawNumber(raw) ?? ''
      }
      return formatCell(raw, c.format)
    }))
  }
  const ws = XLSX.utils.aoa_to_sheet(aoa)

  // Apply z (number-format) to numeric columns
  table.columns.forEach((c, i) => {
    if (!c.format) return
    let z: string | undefined
    if (c.format === 'currency') z = CURRENCY_FMT
    if (c.format === 'percent')  z = PERCENT_FMT
    if (c.format === 'number')   z = NUMBER_FMT
    if (c.format === 'date')     z = DATE_FMT
    if (!z) return
    const startRow = 2  // headers on row 2 (1-indexed = aoa[1])
    const endRow   = startRow + table.rows.length + (table.totals ? 1 : 0)
    for (let r = startRow; r < endRow; r++) {
      const cellRef = XLSX.utils.encode_cell({ r, c: i })
      const cell = ws[cellRef]
      if (cell) cell.z = z
    }
  })

  // Freeze the header row + bold it (no rich style support without xlsx-style; basic only)
  ws['!freeze'] = { ySplit: 2 }
  return ws
}

export function payloadToXlsx(payload: ReportExportPayload): Buffer {
  const wb = XLSX.utils.book_new()

  // First sheet: report metadata + KPIs
  const meta: any[][] = [  // eslint-disable-line @typescript-eslint/no-explicit-any
    [payload.title],
    [payload.subtitle],
    payload.comparisonLabel ? [payload.comparisonLabel] : [''],
    [`Generated by ${payload.generatedBy}`],
    [`Generated at ${payload.generatedAt.toISOString()}`],
    [],
    ['KPI', 'Value', 'Comparison'],
    ...payload.kpis.map((k) => [k.label, k.value, k.comparison ?? '']),
  ]
  const summary = XLSX.utils.aoa_to_sheet(meta)
  XLSX.utils.book_append_sheet(wb, summary, 'Summary')

  // One sheet per table
  for (const table of payload.tables) {
    const sheetName = table.title.slice(0, 31).replace(/[\\/?*[\]]/g, ' ')  // Excel limits
    XLSX.utils.book_append_sheet(wb, tableToSheet(table), sheetName)
  }

  return XLSX.write(wb, { type: 'buffer', bookType: 'xlsx' }) as Buffer
}
